# Generated by Django 4.0.5 on 2022-06-13 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=255, verbose_name='First Name')),
                ('user_lname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('user_position', models.CharField(max_length=255, verbose_name='Position')),
                ('pub_date', models.DateField(default=datetime.datetime(2022, 6, 13, 8, 51, 6, 321644, tzinfo=utc))),
            ],
        ),
    ]
