# Generated by Django 4.0.5 on 2022-06-14 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=users.models.image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 2, 59, 20, 612326, tzinfo=utc)),
        ),
    ]
