# Generated by Django 4.0.5 on 2022-06-14 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_pub_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 5, 43, 9, 790309, tzinfo=utc)),
        ),
    ]
