# Generated by Django 4.0.5 on 2022-06-15 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_comment_created_on_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 8, 35, 28, 965661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 8, 35, 28, 965661, tzinfo=utc)),
        ),
    ]
